// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package com.alibaba.nacos.consistency.entity;

public final class Consistency {
  private Consistency() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WriteRequest_ExtendInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WriteRequest_ExtendInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadRequest_ExtendInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadRequest_ExtendInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021consistency.proto\"\277\001\n\014WriteRequest\022\r\n\005" +
      "group\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\022\014" +
      "\n\004type\030\004 \001(\t\022\021\n\toperation\030\005 \001(\t\0221\n\nexten" +
      "dInfo\030\006 \003(\0132\035.WriteRequest.ExtendInfoEnt" +
      "ry\0321\n\017ExtendInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001\"\217\001\n\013ReadRequest\022\r\n\005group\030\001" +
      " \001(\t\022\014\n\004data\030\002 \001(\014\0220\n\nextendInfo\030\003 \003(\0132\034" +
      ".ReadRequest.ExtendInfoEntry\0321\n\017ExtendIn" +
      "foEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"" +
      "9\n\010Response\022\014\n\004data\030\001 \001(\014\022\016\n\006errMsg\030\002 \001(" +
      "\t\022\017\n\007success\030\003 \001(\010B(\n$com.alibaba.nacos." +
      "consistency.entityP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WriteRequest_descriptor,
        new java.lang.String[] { "Group", "Key", "Data", "Type", "Operation", "ExtendInfo", });
    internal_static_WriteRequest_ExtendInfoEntry_descriptor =
      internal_static_WriteRequest_descriptor.getNestedTypes().get(0);
    internal_static_WriteRequest_ExtendInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WriteRequest_ExtendInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadRequest_descriptor,
        new java.lang.String[] { "Group", "Data", "ExtendInfo", });
    internal_static_ReadRequest_ExtendInfoEntry_descriptor =
      internal_static_ReadRequest_descriptor.getNestedTypes().get(0);
    internal_static_ReadRequest_ExtendInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadRequest_ExtendInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Data", "ErrMsg", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
