// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package com.alibaba.nacos.consistency.entity;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string errMsg = 2;</code>
   */
  String getErrMsg();
  /**
   * <code>string errMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrMsgBytes();
}
