# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
    - good first issue
    - contribution welcome
    - dependencies
    - kind/bug
    - kind/code quality
    - kind/enhancement
    - kind/performance
    - kind/proposal
    - kind/refactor
    - kind/feature
    - kind/user experience
    - Soc2019
    - SoC2020
    - kind/notice
# Label to use when marking an issue as stale
staleLabel: expired
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
    Thanks for your feedback and contribution. But the issue/pull request has
    not had recent activity more than **180 days**. This issue/pull request will
    be closed if no further activity occurs **7 days later**.

    We may solve this issue in new version. So can you upgrade to newest version
    and retry?

    If there are still issues or want to contribute again. Please create new issue
    or pull request again.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
