/*
 * Copyright 1999-2026 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.alibaba.nacos.ai.service.search;

/**
 * Search text generated by an AI resource index enhancement provider.
 *
 * @author nacos
 */
public class AiResourceIndexEnhancementChunk {
    
    private final String chunkType;
    
    private final String text;
    
    private final String metadata;
    
    public AiResourceIndexEnhancementChunk(String chunkType, String text, String metadata) {
        this.chunkType = chunkType;
        this.text = text;
        this.metadata = metadata;
    }
    
    public String getChunkType() {
        return chunkType;
    }
    
    public String getText() {
        return text;
    }
    
    public String getMetadata() {
        return metadata;
    }
}
