// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_grpc_service.proto

package com.alibaba.nacos.core.remoting.grpc;

/**
 * Protobuf type {@code GrpcConnection}
 */
public  final class GrpcConnection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcConnection)
    GrpcConnectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcConnection.newBuilder() to construct.
  private GrpcConnection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcConnection() {
    connectionId_ = "";
    connectionType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcConnection();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GrpcConnection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            connectionId_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            connectionType_ = rawValue;
            break;
          }
          case 34: {
            com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.Builder subBuilder = null;
            if (metadata_ != null) {
              subBuilder = metadata_.toBuilder();
            }
            metadata_ = input.readMessage(com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadata_);
              metadata_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alibaba.nacos.core.remoting.grpc.BaseGrpcService.internal_static_GrpcConnection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alibaba.nacos.core.remoting.grpc.BaseGrpcService.internal_static_GrpcConnection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alibaba.nacos.core.remoting.grpc.GrpcConnection.class, com.alibaba.nacos.core.remoting.grpc.GrpcConnection.Builder.class);
  }

  public static final int CONNECTION_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object connectionId_;
  /**
   * <code>string connection_id = 1;</code>
   * @return The connectionId.
   */
  public java.lang.String getConnectionId() {
    java.lang.Object ref = connectionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      connectionId_ = s;
      return s;
    }
  }
  /**
   * <code>string connection_id = 1;</code>
   * @return The bytes for connectionId.
   */
  public com.google.protobuf.ByteString
      getConnectionIdBytes() {
    java.lang.Object ref = connectionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      connectionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONNECTION_TYPE_FIELD_NUMBER = 3;
  private int connectionType_;
  /**
   * <code>.ConnectionType connection_type = 3;</code>
   * @return The enum numeric value on the wire for connectionType.
   */
  public int getConnectionTypeValue() {
    return connectionType_;
  }
  /**
   * <code>.ConnectionType connection_type = 3;</code>
   * @return The connectionType.
   */
  public com.alibaba.nacos.core.remoting.grpc.ConnectionType getConnectionType() {
    @SuppressWarnings("deprecation")
    com.alibaba.nacos.core.remoting.grpc.ConnectionType result = com.alibaba.nacos.core.remoting.grpc.ConnectionType.valueOf(connectionType_);
    return result == null ? com.alibaba.nacos.core.remoting.grpc.ConnectionType.UNRECOGNIZED : result;
  }

  public static final int METADATA_FIELD_NUMBER = 4;
  private com.alibaba.nacos.core.remoting.grpc.GrpcMetadata metadata_;
  /**
   * <code>.GrpcMetadata metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  public boolean hasMetadata() {
    return metadata_ != null;
  }
  /**
   * <code>.GrpcMetadata metadata = 4;</code>
   * @return The metadata.
   */
  public com.alibaba.nacos.core.remoting.grpc.GrpcMetadata getMetadata() {
    return metadata_ == null ? com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.GrpcMetadata metadata = 4;</code>
   */
  public com.alibaba.nacos.core.remoting.grpc.GrpcMetadataOrBuilder getMetadataOrBuilder() {
    return getMetadata();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getConnectionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, connectionId_);
    }
    if (connectionType_ != com.alibaba.nacos.core.remoting.grpc.ConnectionType.DEFAULT.getNumber()) {
      output.writeEnum(3, connectionType_);
    }
    if (metadata_ != null) {
      output.writeMessage(4, getMetadata());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getConnectionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, connectionId_);
    }
    if (connectionType_ != com.alibaba.nacos.core.remoting.grpc.ConnectionType.DEFAULT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, connectionType_);
    }
    if (metadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMetadata());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alibaba.nacos.core.remoting.grpc.GrpcConnection)) {
      return super.equals(obj);
    }
    com.alibaba.nacos.core.remoting.grpc.GrpcConnection other = (com.alibaba.nacos.core.remoting.grpc.GrpcConnection) obj;

    if (!getConnectionId()
        .equals(other.getConnectionId())) return false;
    if (connectionType_ != other.connectionType_) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONNECTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConnectionId().hashCode();
    hash = (37 * hash) + CONNECTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + connectionType_;
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alibaba.nacos.core.remoting.grpc.GrpcConnection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcConnection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcConnection)
      com.alibaba.nacos.core.remoting.grpc.GrpcConnectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.nacos.core.remoting.grpc.BaseGrpcService.internal_static_GrpcConnection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.nacos.core.remoting.grpc.BaseGrpcService.internal_static_GrpcConnection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.nacos.core.remoting.grpc.GrpcConnection.class, com.alibaba.nacos.core.remoting.grpc.GrpcConnection.Builder.class);
    }

    // Construct using com.alibaba.nacos.core.remoting.grpc.GrpcConnection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      connectionId_ = "";

      connectionType_ = 0;

      if (metadataBuilder_ == null) {
        metadata_ = null;
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alibaba.nacos.core.remoting.grpc.BaseGrpcService.internal_static_GrpcConnection_descriptor;
    }

    @java.lang.Override
    public com.alibaba.nacos.core.remoting.grpc.GrpcConnection getDefaultInstanceForType() {
      return com.alibaba.nacos.core.remoting.grpc.GrpcConnection.getDefaultInstance();
    }

    @java.lang.Override
    public com.alibaba.nacos.core.remoting.grpc.GrpcConnection build() {
      com.alibaba.nacos.core.remoting.grpc.GrpcConnection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alibaba.nacos.core.remoting.grpc.GrpcConnection buildPartial() {
      com.alibaba.nacos.core.remoting.grpc.GrpcConnection result = new com.alibaba.nacos.core.remoting.grpc.GrpcConnection(this);
      result.connectionId_ = connectionId_;
      result.connectionType_ = connectionType_;
      if (metadataBuilder_ == null) {
        result.metadata_ = metadata_;
      } else {
        result.metadata_ = metadataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alibaba.nacos.core.remoting.grpc.GrpcConnection) {
        return mergeFrom((com.alibaba.nacos.core.remoting.grpc.GrpcConnection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alibaba.nacos.core.remoting.grpc.GrpcConnection other) {
      if (other == com.alibaba.nacos.core.remoting.grpc.GrpcConnection.getDefaultInstance()) return this;
      if (!other.getConnectionId().isEmpty()) {
        connectionId_ = other.connectionId_;
        onChanged();
      }
      if (other.connectionType_ != 0) {
        setConnectionTypeValue(other.getConnectionTypeValue());
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alibaba.nacos.core.remoting.grpc.GrpcConnection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alibaba.nacos.core.remoting.grpc.GrpcConnection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object connectionId_ = "";
    /**
     * <code>string connection_id = 1;</code>
     * @return The connectionId.
     */
    public java.lang.String getConnectionId() {
      java.lang.Object ref = connectionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connectionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string connection_id = 1;</code>
     * @return The bytes for connectionId.
     */
    public com.google.protobuf.ByteString
        getConnectionIdBytes() {
      java.lang.Object ref = connectionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string connection_id = 1;</code>
     * @param value The connectionId to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      connectionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string connection_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionId() {
      
      connectionId_ = getDefaultInstance().getConnectionId();
      onChanged();
      return this;
    }
    /**
     * <code>string connection_id = 1;</code>
     * @param value The bytes for connectionId to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      connectionId_ = value;
      onChanged();
      return this;
    }

    private int connectionType_ = 0;
    /**
     * <code>.ConnectionType connection_type = 3;</code>
     * @return The enum numeric value on the wire for connectionType.
     */
    public int getConnectionTypeValue() {
      return connectionType_;
    }
    /**
     * <code>.ConnectionType connection_type = 3;</code>
     * @param value The enum numeric value on the wire for connectionType to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionTypeValue(int value) {
      connectionType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ConnectionType connection_type = 3;</code>
     * @return The connectionType.
     */
    public com.alibaba.nacos.core.remoting.grpc.ConnectionType getConnectionType() {
      @SuppressWarnings("deprecation")
      com.alibaba.nacos.core.remoting.grpc.ConnectionType result = com.alibaba.nacos.core.remoting.grpc.ConnectionType.valueOf(connectionType_);
      return result == null ? com.alibaba.nacos.core.remoting.grpc.ConnectionType.UNRECOGNIZED : result;
    }
    /**
     * <code>.ConnectionType connection_type = 3;</code>
     * @param value The connectionType to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionType(com.alibaba.nacos.core.remoting.grpc.ConnectionType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      connectionType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ConnectionType connection_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionType() {
      
      connectionType_ = 0;
      onChanged();
      return this;
    }

    private com.alibaba.nacos.core.remoting.grpc.GrpcMetadata metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.alibaba.nacos.core.remoting.grpc.GrpcMetadata, com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.Builder, com.alibaba.nacos.core.remoting.grpc.GrpcMetadataOrBuilder> metadataBuilder_;
    /**
     * <code>.GrpcMetadata metadata = 4;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return metadataBuilder_ != null || metadata_ != null;
    }
    /**
     * <code>.GrpcMetadata metadata = 4;</code>
     * @return The metadata.
     */
    public com.alibaba.nacos.core.remoting.grpc.GrpcMetadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.GrpcMetadata metadata = 4;</code>
     */
    public Builder setMetadata(com.alibaba.nacos.core.remoting.grpc.GrpcMetadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.GrpcMetadata metadata = 4;</code>
     */
    public Builder setMetadata(
        com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.GrpcMetadata metadata = 4;</code>
     */
    public Builder mergeMetadata(com.alibaba.nacos.core.remoting.grpc.GrpcMetadata value) {
      if (metadataBuilder_ == null) {
        if (metadata_ != null) {
          metadata_ =
            com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.newBuilder(metadata_).mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        metadataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.GrpcMetadata metadata = 4;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = null;
        onChanged();
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.GrpcMetadata metadata = 4;</code>
     */
    public com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.Builder getMetadataBuilder() {
      
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.GrpcMetadata metadata = 4;</code>
     */
    public com.alibaba.nacos.core.remoting.grpc.GrpcMetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.GrpcMetadata metadata = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.alibaba.nacos.core.remoting.grpc.GrpcMetadata, com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.Builder, com.alibaba.nacos.core.remoting.grpc.GrpcMetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.alibaba.nacos.core.remoting.grpc.GrpcMetadata, com.alibaba.nacos.core.remoting.grpc.GrpcMetadata.Builder, com.alibaba.nacos.core.remoting.grpc.GrpcMetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcConnection)
  }

  // @@protoc_insertion_point(class_scope:GrpcConnection)
  private static final com.alibaba.nacos.core.remoting.grpc.GrpcConnection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alibaba.nacos.core.remoting.grpc.GrpcConnection();
  }

  public static com.alibaba.nacos.core.remoting.grpc.GrpcConnection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcConnection>
      PARSER = new com.google.protobuf.AbstractParser<GrpcConnection>() {
    @java.lang.Override
    public GrpcConnection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GrpcConnection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcConnection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcConnection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alibaba.nacos.core.remoting.grpc.GrpcConnection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

