// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_grpc_service.proto

package com.alibaba.nacos.core.remoting.grpc;

public interface GrpcResourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcResource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Common metadata describing the resource.
   * </pre>
   *
   * <code>.GrpcMetadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Common metadata describing the resource.
   * </pre>
   *
   * <code>.GrpcMetadata metadata = 1;</code>
   * @return The metadata.
   */
  com.alibaba.nacos.core.remoting.grpc.GrpcMetadata getMetadata();
  /**
   * <pre>
   * Common metadata describing the resource.
   * </pre>
   *
   * <code>.GrpcMetadata metadata = 1;</code>
   */
  com.alibaba.nacos.core.remoting.grpc.GrpcMetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * The primary payload for the resource.
   * </pre>
   *
   * <code>.google.protobuf.Any body = 2;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <pre>
   * The primary payload for the resource.
   * </pre>
   *
   * <code>.google.protobuf.Any body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.Any getBody();
  /**
   * <pre>
   * The primary payload for the resource.
   * </pre>
   *
   * <code>.google.protobuf.Any body = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
}
