// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package com.alibaba.nacos.istio.model.mcp;

public final class MetadataOuterClass {
  private MetadataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_mcp_v1alpha1_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_mcp_v1alpha1_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_mcp_v1alpha1_Metadata_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_mcp_v1alpha1_Metadata_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_mcp_v1alpha1_Metadata_AnnotationsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_mcp_v1alpha1_Metadata_AnnotationsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016metadata.proto\022\022istio.mcp.v1alpha1\032\037go" +
      "ogle/protobuf/timestamp.proto\"\273\002\n\010Metada" +
      "ta\022\014\n\004name\030\001 \001(\t\022/\n\013create_time\030\002 \001(\0132\032." +
      "google.protobuf.Timestamp\022\017\n\007version\030\003 \001" +
      "(\t\0228\n\006labels\030\004 \003(\0132(.istio.mcp.v1alpha1." +
      "Metadata.LabelsEntry\022B\n\013annotations\030\005 \003(" +
      "\0132-.istio.mcp.v1alpha1.Metadata.Annotati" +
      "onsEntry\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\0322\n\020AnnotationsEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B%\n!com.aliba" +
      "ba.nacos.istio.model.mcpP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_istio_mcp_v1alpha1_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_istio_mcp_v1alpha1_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_mcp_v1alpha1_Metadata_descriptor,
        new java.lang.String[] { "Name", "CreateTime", "Version", "Labels", "Annotations", });
    internal_static_istio_mcp_v1alpha1_Metadata_LabelsEntry_descriptor =
      internal_static_istio_mcp_v1alpha1_Metadata_descriptor.getNestedTypes().get(0);
    internal_static_istio_mcp_v1alpha1_Metadata_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_mcp_v1alpha1_Metadata_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_istio_mcp_v1alpha1_Metadata_AnnotationsEntry_descriptor =
      internal_static_istio_mcp_v1alpha1_Metadata_descriptor.getNestedTypes().get(1);
    internal_static_istio_mcp_v1alpha1_Metadata_AnnotationsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_mcp_v1alpha1_Metadata_AnnotationsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
