/*
 * Copyright 1999-2026 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.alibaba.nacos.config.server.service.repository;

import com.alibaba.nacos.config.server.service.repository.embedded.EmbeddedConfigInfoPersistServiceImpl;
import com.alibaba.nacos.plugin.datasource.constants.FieldConstant;
import com.alibaba.nacos.plugin.datasource.impl.derby.ConfigInfoMapperByDerby;
import com.alibaba.nacos.plugin.datasource.model.MapperContext;
import com.alibaba.nacos.plugin.datasource.model.MapperResult;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Executes the LIKE statement generated by the Derby mapper against a real in-memory Derby database,
 * binding the parameter produced by {@link ConfigInfoPersistService#generateLikeArgument(String)}.
 *
 * <p>Derby has no default LIKE escape character, so the mapper declares {@code ESCAPE '\'} explicitly.
 * That makes the emitted SQL and the bound parameter a single contract: asserting the SQL text alone
 * cannot detect an invalid escape sequence in the parameter, which Derby only rejects at execution
 * time with {@code SQLSTATE 22025}. This test exercises both halves together.</p>
 *
 * @author nacos
 */
class ConfigInfoLikeEscapeDerbyTest {
    
    private static final String JDBC_URL = "jdbc:derby:memory:configInfoLikeEscapeTest;create=true";
    
    /**
     * Matches every tenant, so the assertions only depend on the data_id predicate.
     */
    private static final String ANY_TENANT = "*";
    
    private static Connection connection;
    
    private final ConfigInfoPersistService persistService = Mockito.mock(
        EmbeddedConfigInfoPersistServiceImpl.class, Mockito.CALLS_REAL_METHODS);
    
    private final ConfigInfoMapperByDerby configInfoMapperByDerby = new ConfigInfoMapperByDerby();
    
    @BeforeAll
    static void initDatabase() throws SQLException {
        connection = DriverManager.getConnection(JDBC_URL);
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE config_info (id BIGINT, data_id VARCHAR(255), "
                + "group_id VARCHAR(128), tenant_id VARCHAR(128), content VARCHAR(255), "
                + "app_name VARCHAR(128), type VARCHAR(64))");
        }
        insertDataId(1L, "nacos_test");
        insertDataId(2L, "nacosXtest");
        insertDataId(3L, "C:\\path");
        insertDataId(4L, "a\\_b");
        insertDataId(5L, "a\\Xb");
        insertDataId(6L, "trail\\");
    }
    
    @AfterAll
    static void destroyDatabase() throws SQLException {
        if (null != connection) {
            connection.close();
        }
    }
    
    private static void insertDataId(long id, String dataId) throws SQLException {
        String sql = "INSERT INTO config_info (id, data_id, group_id, tenant_id, content, "
            + "app_name, type) VALUES (?, ?, 'group', '', 'content', 'app', 'text')";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setLong(1, id);
            statement.setString(2, dataId);
            statement.executeUpdate();
        }
    }
    
    @Test
    void testUnderscoreIsMatchedLiterally() throws SQLException {
        assertEquals(1, countByDataIdPattern("*nacos_test*"));
    }
    
    @Test
    void testBackslashInSearchValueIsAccepted() throws SQLException {
        assertEquals(1, countByDataIdPattern("*C:\\path*"));
    }
    
    @Test
    void testTrailingBackslashInSearchValueIsAccepted() throws SQLException {
        assertEquals(1, countByDataIdPattern("*trail\\*"));
    }
    
    @Test
    void testEscapedUnderscoreAfterBackslashIsMatchedLiterally() throws SQLException {
        assertEquals(1, countByDataIdPattern("*a\\_b*"));
    }
    
    /**
     * Counts the rows matched by the SQL the Derby mapper generates, binding the parameters produced
     * by the persist service. Throws {@link SQLException} if the escaped argument is invalid.
     */
    private int countByDataIdPattern(String dataIdPattern) throws SQLException {
        MapperContext context = new MapperContext();
        context.putWhereParameter(FieldConstant.TENANT_ID,
            persistService.generateLikeArgument(ANY_TENANT));
        context.putWhereParameter(FieldConstant.DATA_ID,
            persistService.generateLikeArgument(dataIdPattern));
        MapperResult mapperResult =
            configInfoMapperByDerby.findConfigInfoLike4PageCountRows(context);
        assertTrue(mapperResult.getSql().contains("ESCAPE '\\'"),
            "Derby must declare the LIKE escape clause: " + mapperResult.getSql());
        
        try (PreparedStatement statement = connection.prepareStatement(mapperResult.getSql())) {
            List<Object> paramList = mapperResult.getParamList();
            for (int i = 0; i < paramList.size(); i++) {
                statement.setObject(i + 1, paramList.get(i));
            }
            try (ResultSet resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getInt(1);
            }
        }
    }
}
