/*
 * Copyright 1999-2026 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.alibaba.nacos.ai.service.search;

import com.alibaba.nacos.ai.model.search.AiResourceSearchChunk;
import com.alibaba.nacos.ai.model.search.AiResourceSearchDocument;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tests for {@link JdbcAiResourceSearchRepository}.
 *
 * @author nacos
 */
class JdbcAiResourceSearchRepositoryTest {
    
    private JdbcTemplate jdbcTemplate;
    
    private JdbcAiResourceSearchRepository repository;
    
    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL(
            "jdbc:h2:mem:ard_index_repository;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("DROP TABLE IF EXISTS ai_resource_search_chunk");
        jdbcTemplate.execute("DROP TABLE IF EXISTS ai_resource_search_document");
        createSearchTables(jdbcTemplate);
        repository = new JdbcAiResourceSearchRepository(jdbcTemplate);
    }
    
    @Test
    void replaceEntryShouldReadGeneratedKeysFromDerbyIdentityColumns() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.apache.derby.jdbc.EmbeddedDriver");
        dataSource.setUrl("jdbc:derby:memory:ard_index_repository_derby;create=true");
        JdbcTemplate derbyTemplate = new JdbcTemplate(dataSource);
        createSearchTables(derbyTemplate);
        JdbcAiResourceSearchRepository derbyRepository =
            new JdbcAiResourceSearchRepository(derbyTemplate);
        AiResourceSearchDocument entry = entry("derby");
        
        List<AiResourceSearchChunk> chunks =
            derbyRepository.replaceEntry(entry, List.of(chunk("derby", "derby")));
        
        assertNotNull(entry.getId());
        assertEquals(1, chunks.size());
        assertNotNull(chunks.get(0).getId());
    }
    
    private void createSearchTables(JdbcTemplate template) {
        template.execute("CREATE TABLE ai_resource_search_document ("
            + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "namespace_id varchar(128) NOT NULL, resource_type varchar(32) NOT NULL,"
            + "resource_name varchar(256) NOT NULL, resource_version varchar(64) NOT NULL,"
            + "display_name varchar(256) NOT NULL, c_desc varchar(2048), tags clob,"
            + "capabilities clob, representative_queries clob, metadata clob,"
            + "source_digest varchar(64) NOT NULL, status varchar(32) NOT NULL,"
            + "generate_mode varchar(32) NOT NULL, gmt_create timestamp NOT NULL,"
            + "gmt_modified timestamp NOT NULL,"
            + "UNIQUE(namespace_id, resource_type, resource_name, resource_version))");
        template.execute("CREATE TABLE ai_resource_search_chunk ("
            + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id bigint NOT NULL,"
            + "namespace_id varchar(128) NOT NULL, resource_type varchar(32) NOT NULL,"
            + "resource_name varchar(256) NOT NULL, resource_version varchar(64) NOT NULL,"
            + "chunk_type varchar(64) NOT NULL, chunk_text varchar(4096) NOT NULL,"
            + "canonical_text varchar(4096) NOT NULL, language varchar(16),"
            + "chunk_hash varchar(64) NOT NULL, metadata clob, status varchar(32) NOT NULL,"
            + "gmt_create timestamp NOT NULL, gmt_modified timestamp NOT NULL)");
    }
    
    @Test
    void replaceEntryShouldRollbackDeleteAndPartialInsert() {
        jdbcTemplate.update("INSERT INTO ai_resource_search_document "
            + "(namespace_id, resource_type, resource_name, resource_version, display_name, "
            + "source_digest, status, generate_mode, gmt_create, gmt_modified) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
            "public", "skill", "avatar", "1.0.0", "old", "old-digest", "enabled", "auto");
        Long oldDocumentId = jdbcTemplate.queryForObject(
            "SELECT id FROM ai_resource_search_document WHERE display_name='old'", Long.class);
        jdbcTemplate.update("INSERT INTO ai_resource_search_chunk "
            + "(document_id, namespace_id, resource_type, resource_name, resource_version, "
            + "chunk_type, chunk_text, canonical_text, chunk_hash, status, "
            + "gmt_create, gmt_modified) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, "
            + "CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
            oldDocumentId, "public", "skill", "avatar", "1.0.0", "description", "old", "old",
            "old-hash", "enabled");
        
        AiResourceSearchDocument replacement = entry("new");
        AiResourceSearchChunk validChunk = chunk("valid", "valid");
        AiResourceSearchChunk invalidChunk = chunk("invalid", null);
        
        assertThrows(DataIntegrityViolationException.class,
            () -> repository.replaceEntry(replacement, List.of(validChunk, invalidChunk)));
        
        assertEquals("old", jdbcTemplate.queryForObject(
            "SELECT display_name FROM ai_resource_search_document", String.class));
        assertEquals(1, jdbcTemplate.queryForObject(
            "SELECT COUNT(1) FROM ai_resource_search_chunk", Integer.class));
    }
    
    @Test
    void queriesShouldApplyRowBoundsInJdbc() {
        for (int i = 1; i <= 5; i++) {
            jdbcTemplate.update("INSERT INTO ai_resource_search_document "
                + "(namespace_id, resource_type, resource_name, resource_version, display_name, "
                + "source_digest, status, generate_mode, gmt_create, gmt_modified) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                "public", "skill", "skill-" + i, "1.0.0", "skill-" + i, "digest-" + i,
                "enabled", "auto");
        }
        
        assertEquals(2,
            repository.listEnabledEntries("public", List.of("skill"), 2).size());
        assertEquals(2,
            repository.scanEnabledEntries("public", List.of("skill"), 0L, 2).size());
    }
    
    @Test
    void resourceKeyScanShouldUseStableCompositeAnchor() {
        insertEntry("skill", "bravo", "1.0.0");
        insertEntry("mcp", "alpha", "1.0.0");
        insertEntry("skill", "alpha", "1.0.0");
        insertEntry("skill", "alpha", "2.0.0");
        
        List<AiResourceSearchDocument> all = repository.scanEnabledEntriesByResourceKey(
            "public", List.of(), null, null, 0L, 10);
        assertEquals(List.of("mcp:alpha:1.0.0", "skill:alpha:1.0.0",
            "skill:alpha:2.0.0", "skill:bravo:1.0.0"), resourceKeys(all));
        AiResourceSearchDocument firstAlpha = all.get(1);
        List<AiResourceSearchDocument> continuation =
            repository.scanEnabledEntriesByResourceKey("public", List.of("skill"),
                firstAlpha.getResourceType(), firstAlpha.getResourceName(), firstAlpha.getId(), 10);
        assertEquals(List.of("skill:alpha:2.0.0", "skill:bravo:1.0.0"),
            resourceKeys(continuation));
        assertEquals(0, repository.scanEnabledEntriesByResourceKey("public", List.of(), null,
            null, 0L, 0).size());
    }
    
    @Test
    void replaceEnhancementChunksShouldBeIdempotentAndKeepBaseChunks() {
        AiResourceSearchDocument entry = entry("avatar");
        AiResourceSearchChunk baseChunk = typedChunk(
            AiResourceSearchConstants.CHUNK_TYPE_DESCRIPTION, "base");
        AiResourceSearchChunk oldEnhancement = typedChunk(
            AiResourceSearchConstants.CHUNK_TYPE_AI_SUMMARY, "old-summary");
        repository.replaceEntry(entry, List.of(baseChunk, oldEnhancement));
        
        AiResourceSearchChunk newEnhancement = typedChunk(
            AiResourceSearchConstants.CHUNK_TYPE_SEARCH_TERM, "avatar generator");
        repository.replaceEnhancementChunks(entry, List.of(newEnhancement));
        List<AiResourceSearchChunk> secondReplacement =
            repository.replaceEnhancementChunks(entry, List.of(typedChunk(
                AiResourceSearchConstants.CHUNK_TYPE_SEARCH_TERM, "avatar generator")));
        
        assertEquals(2, secondReplacement.size());
        assertEquals(1, secondReplacement.stream().filter(
            chunk -> AiResourceSearchConstants.CHUNK_TYPE_DESCRIPTION.equals(chunk.getChunkType()))
            .count());
        assertEquals(1, secondReplacement.stream().filter(
            chunk -> AiResourceSearchConstants.CHUNK_TYPE_SEARCH_TERM.equals(chunk.getChunkType()))
            .count());
    }
    
    private AiResourceSearchDocument entry(String displayName) {
        AiResourceSearchDocument entry = new AiResourceSearchDocument();
        entry.setNamespaceId("public");
        entry.setResourceType("skill");
        entry.setResourceName("avatar");
        entry.setResourceVersion("1.0.0");
        entry.setDisplayName(displayName);
        entry.setSourceDigest("new-digest");
        entry.setStatus(AiResourceSearchConstants.STATUS_ENABLED);
        entry.setGenerateMode(AiResourceSearchConstants.GENERATE_MODE_AUTO);
        return entry;
    }
    
    private void insertEntry(String resourceType, String resourceName, String version) {
        jdbcTemplate.update("INSERT INTO ai_resource_search_document "
            + "(namespace_id, resource_type, resource_name, resource_version, display_name, "
            + "source_digest, status, generate_mode, gmt_create, gmt_modified) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
            "public", resourceType, resourceName, version, resourceName,
            resourceType + "-" + resourceName + "-" + version,
            AiResourceSearchConstants.STATUS_ENABLED, AiResourceSearchConstants.GENERATE_MODE_AUTO);
    }
    
    private List<String> resourceKeys(List<AiResourceSearchDocument> documents) {
        return documents.stream().map(document -> document.getResourceType() + ":"
            + document.getResourceName() + ":" + document.getResourceVersion()).toList();
    }
    
    private AiResourceSearchChunk chunk(String text, String canonicalText) {
        return chunk(AiResourceSearchConstants.CHUNK_TYPE_DESCRIPTION, text, canonicalText);
    }
    
    private AiResourceSearchChunk chunk(String chunkType, String text, String canonicalText) {
        AiResourceSearchChunk chunk = new AiResourceSearchChunk();
        chunk.setChunkType(chunkType);
        chunk.setChunkText(text);
        chunk.setCanonicalText(canonicalText);
        chunk.setChunkHash(text + "-hash");
        chunk.setStatus(AiResourceSearchConstants.STATUS_ENABLED);
        return chunk;
    }
    
    private AiResourceSearchChunk typedChunk(String chunkType, String text) {
        return chunk(chunkType, text, text);
    }
}
