/*
 * Copyright 1999-2026 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.alibaba.nacos.ai.service.search;

import com.alibaba.nacos.ai.model.search.AiResourceSearchChunk;
import com.alibaba.nacos.ai.model.search.AiResourceSearchDocument;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tests for {@link JdbcAiResourceSearchRepository}.
 *
 * @author nacos
 */
class JdbcAiResourceSearchRepositoryTest {
    
    private JdbcTemplate jdbcTemplate;
    
    private JdbcAiResourceSearchRepository repository;
    
    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:ard_index_repository;DB_CLOSE_DELAY=-1");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("DROP TABLE IF EXISTS ai_resource_search_chunk");
        jdbcTemplate.execute("DROP TABLE IF EXISTS ai_resource_search_document");
        jdbcTemplate.execute("CREATE TABLE ai_resource_search_document ("
            + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "namespace_id varchar(128) NOT NULL, resource_type varchar(32) NOT NULL,"
            + "resource_name varchar(256) NOT NULL, resource_version varchar(64) NOT NULL,"
            + "display_name varchar(256) NOT NULL, c_desc varchar(2048), tags clob,"
            + "capabilities clob, representative_queries clob, metadata clob,"
            + "source_digest varchar(64) NOT NULL, status varchar(32) NOT NULL,"
            + "generate_mode varchar(32) NOT NULL, gmt_create timestamp NOT NULL,"
            + "gmt_modified timestamp NOT NULL,"
            + "UNIQUE(namespace_id, resource_type, resource_name, resource_version))");
        jdbcTemplate.execute("CREATE TABLE ai_resource_search_chunk ("
            + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id bigint NOT NULL,"
            + "namespace_id varchar(128) NOT NULL, resource_type varchar(32) NOT NULL,"
            + "resource_name varchar(256) NOT NULL, resource_version varchar(64) NOT NULL,"
            + "chunk_type varchar(64) NOT NULL, chunk_text varchar(4096) NOT NULL,"
            + "canonical_text varchar(4096) NOT NULL, language varchar(16),"
            + "chunk_hash varchar(64) NOT NULL, metadata clob, status varchar(32) NOT NULL,"
            + "gmt_create timestamp NOT NULL, gmt_modified timestamp NOT NULL)");
        repository = new JdbcAiResourceSearchRepository(jdbcTemplate);
    }
    
    @Test
    void replaceEntryShouldRollbackDeleteAndPartialInsert() {
        jdbcTemplate.update("INSERT INTO ai_resource_search_document "
            + "(namespace_id, resource_type, resource_name, resource_version, display_name, "
            + "source_digest, status, generate_mode, gmt_create, gmt_modified) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
            "public", "skill", "avatar", "1.0.0", "old", "old-digest", "enabled", "auto");
        Long oldDocumentId = jdbcTemplate.queryForObject(
            "SELECT id FROM ai_resource_search_document WHERE display_name='old'", Long.class);
        jdbcTemplate.update("INSERT INTO ai_resource_search_chunk "
            + "(document_id, namespace_id, resource_type, resource_name, resource_version, "
            + "chunk_type, chunk_text, canonical_text, chunk_hash, status, "
            + "gmt_create, gmt_modified) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, "
            + "CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
            oldDocumentId, "public", "skill", "avatar", "1.0.0", "description", "old", "old",
            "old-hash", "enabled");
        
        AiResourceSearchDocument replacement = entry("new");
        AiResourceSearchChunk validChunk = chunk("valid", "valid");
        AiResourceSearchChunk invalidChunk = chunk("invalid", null);
        
        assertThrows(DataIntegrityViolationException.class,
            () -> repository.replaceEntry(replacement, List.of(validChunk, invalidChunk)));
        
        assertEquals("old", jdbcTemplate.queryForObject(
            "SELECT display_name FROM ai_resource_search_document", String.class));
        assertEquals(1, jdbcTemplate.queryForObject(
            "SELECT COUNT(1) FROM ai_resource_search_chunk", Integer.class));
    }
    
    @Test
    void queriesShouldApplyRowBoundsInJdbc() {
        for (int i = 1; i <= 5; i++) {
            jdbcTemplate.update("INSERT INTO ai_resource_search_document "
                + "(namespace_id, resource_type, resource_name, resource_version, display_name, "
                + "source_digest, status, generate_mode, gmt_create, gmt_modified) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                "public", "skill", "skill-" + i, "1.0.0", "skill-" + i, "digest-" + i,
                "enabled", "auto");
        }
        
        assertEquals(2,
            repository.listEnabledEntries("public", List.of("skill"), 2).size());
        assertEquals(2,
            repository.scanEnabledEntries("public", List.of("skill"), 0L, 2).size());
    }
    
    private AiResourceSearchDocument entry(String displayName) {
        AiResourceSearchDocument entry = new AiResourceSearchDocument();
        entry.setNamespaceId("public");
        entry.setResourceType("skill");
        entry.setResourceName("avatar");
        entry.setResourceVersion("1.0.0");
        entry.setDisplayName(displayName);
        entry.setSourceDigest("new-digest");
        entry.setStatus(AiResourceSearchConstants.STATUS_ENABLED);
        entry.setGenerateMode(AiResourceSearchConstants.GENERATE_MODE_AUTO);
        return entry;
    }
    
    private AiResourceSearchChunk chunk(String text, String canonicalText) {
        AiResourceSearchChunk chunk = new AiResourceSearchChunk();
        chunk.setChunkType(AiResourceSearchConstants.CHUNK_TYPE_DESCRIPTION);
        chunk.setChunkText(text);
        chunk.setCanonicalText(canonicalText);
        chunk.setChunkHash(text + "-hash");
        chunk.setStatus(AiResourceSearchConstants.STATUS_ENABLED);
        return chunk;
    }
}
