pipeline {
  agent any
  tools {
    // Install the Maven version configured as "M3" and add it to the path.
    maven "M3"
  }
  environment {
    projectName = 'msmp-nacos'
    jarName = 'nacos-server'
    envName = 'local'
    suffix = 'zip'
  }
  stages {
    stage('compile') {
      steps {
      	sh 'pwd'
        sh 'mvn clean install -Dmaven.test.skip=true -Prelease-nacos'
      }
    }
    stage('copy resource to dir') {
      steps {
        sh 'pwd'
        sh 'cp distribution/target/*.${suffix} jenkins/${envName}/${jarName}.${suffix}'
      }
    }
    stage('build docker and run') {
      steps {
        sh 'cd jenkins/${envName} && chmod +x deploy.sh && ./deploy.sh'
      }
    }
  }
}