// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_grpc_service.proto

package com.alibaba.nacos.common.grpc;

public final class BaseGrpcService {
  private BaseGrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcMetadata_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcMetadata_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcRequest_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcRequest_ParamsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027base_grpc_service.proto\032\031google/protob" +
      "uf/any.proto\032\037google/protobuf/timestamp." +
      "proto\"\270\001\n\014GrpcMetadata\022\014\n\004name\030\001 \001(\t\022/\n\013" +
      "create_time\030\002 \001(\0132\032.google.protobuf.Time" +
      "stamp\022\017\n\007version\030\003 \001(\t\022)\n\006labels\030\004 \003(\0132\031" +
      ".GrpcMetadata.LabelsEntry\032-\n\013LabelsEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\233\001\n\014Grp" +
      "cResponse\022\021\n\tclient_id\030\001 \001(\t\022\022\n\nrequest_" +
      "id\030\002 \001(\t\022\016\n\006source\030\003 \001(\t\022\014\n\004code\030\004 \001(\005\022%" +
      "\n\007message\030\005 \001(\0132\024.google.protobuf.Any\022\037\n" +
      "\010metadata\030\006 \001(\0132\r.GrpcMetadata\"\221\002\n\013GrpcR" +
      "equest\022\021\n\tclient_id\030\001 \001(\t\022\022\n\nrequest_id\030" +
      "\002 \001(\t\022\016\n\006action\030\003 \001(\t\022\016\n\006source\030\004 \001(\t\022(\n" +
      "\006params\030\005 \003(\0132\030.GrpcRequest.ParamsEntry\022" +
      "\"\n\004body\030\006 \001(\0132\024.google.protobuf.Any\022\037\n\010m" +
      "etadata\030\007 \001(\0132\r.GrpcMetadata\022\016\n\006module\030\010" +
      " \001(\t\022\r\n\005agent\030\t \001(\t\032-\n\013ParamsEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012E\n\021GrpcStream" +
      "Service\0220\n\rstreamRequest\022\014.GrpcRequest\032\r" +
      ".GrpcResponse\"\0000\00127\n\013GrpcService\022(\n\007requ" +
      "est\022\014.GrpcRequest\032\r.GrpcResponse\"\000B!\n\035co" +
      "m.alibaba.nacos.common.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_GrpcMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GrpcMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcMetadata_descriptor,
        new java.lang.String[] { "Name", "CreateTime", "Version", "Labels", });
    internal_static_GrpcMetadata_LabelsEntry_descriptor =
      internal_static_GrpcMetadata_descriptor.getNestedTypes().get(0);
    internal_static_GrpcMetadata_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcMetadata_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcResponse_descriptor,
        new java.lang.String[] { "ClientId", "RequestId", "Source", "Code", "Message", "Metadata", });
    internal_static_GrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcRequest_descriptor,
        new java.lang.String[] { "ClientId", "RequestId", "Action", "Source", "Params", "Body", "Metadata", "Module", "Agent", });
    internal_static_GrpcRequest_ParamsEntry_descriptor =
      internal_static_GrpcRequest_descriptor.getNestedTypes().get(0);
    internal_static_GrpcRequest_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcRequest_ParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
