/*
 * Copyright 1999-2026 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.alibaba.nacos.plugin.auth.impl.persistence;

import com.alibaba.nacos.api.model.Page;
import com.alibaba.nacos.persistence.repository.embedded.operate.DatabaseOperate;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Executes the SQL generated by the embedded role search against a real Derby database.
 *
 * <p>Asserting the generated SQL text alone cannot prove that the {@code ESCAPE} clause applies to
 * the intended {@code LIKE} predicate, because {@code ESCAPE} only qualifies the predicate it
 * immediately follows. Derby is the database behind the embedded storage, so the query is executed
 * here with the same bound parameters the service produces.</p>
 *
 * @author wushiyuan
 */
class RoleSearchLikeEscapeDerbyTest {
    
    private static final String JDBC_URL = "jdbc:derby:memory:auth_like_escape;create=true";
    
    private Connection connection;
    
    @BeforeEach
    void setUp() throws SQLException {
        connection = DriverManager.getConnection(JDBC_URL);
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE roles (username VARCHAR(50), role VARCHAR(50))");
            statement.execute("INSERT INTO roles VALUES ('na_cos', 'ro_le'), ('naXcos', 'roXle')");
        }
    }
    
    @AfterEach
    void tearDown() throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE roles");
        }
        connection.close();
    }
    
    @Test
    void testFindRolesLike4PageMatchesUnderscoreWhenBothFiltersAreUsed() throws SQLException {
        List<String> matched = executeSearch("na_cos", "ro_le");
        
        assertEquals(1, matched.size());
        assertEquals("na_cos/ro_le", matched.get(0));
    }
    
    @Test
    void testFindRolesLike4PageTreatsUnderscoreAsLiteralForTheUsernameFilter() throws SQLException {
        List<String> matched = executeSearch("na_cos", "");
        
        assertEquals(1, matched.size());
        assertEquals("na_cos/ro_le", matched.get(0));
    }
    
    @Test
    void testFindRolesLikeRoleNameTreatsUnderscoreAsLiteralLikeThePagedSearch()
        throws SQLException {
        List<String> matched = new ArrayList<>();
        DatabaseOperate databaseOperate = Mockito.mock(DatabaseOperate.class);
        Mockito.when(databaseOperate.queryMany(Mockito.anyString(), Mockito.any(Object[].class),
            Mockito.eq(String.class))).thenAnswer(invocation -> {
                matched.addAll(queryRoles(invocation.getArgument(0), invocation.getArgument(1)));
                return matched;
            });
        
        new EmbeddedRolePersistServiceImpl(databaseOperate).findRolesLikeRoleName("ro_le");
        
        assertEquals(1, matched.size());
        assertEquals("ro_le", matched.get(0));
    }
    
    private List<String> queryRoles(String sql, Object[] args) throws SQLException {
        List<String> rows = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            for (int i = 0; i < args.length; i++) {
                statement.setObject(i + 1, args[i]);
            }
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    rows.add(resultSet.getString("role"));
                }
            }
        }
        return rows;
    }
    
    private List<String> executeSearch(String username, String role) {
        List<String> matched = new ArrayList<>();
        serviceExecutingOnDerby(matched).findRolesLike4Page(username, role, 1, 10);
        return matched;
    }
    
    @SuppressWarnings("unchecked")
    private EmbeddedRolePersistServiceImpl serviceExecutingOnDerby(List<String> matched) {
        AuthPaginationHelper<RoleInfo> helper = Mockito.mock(AuthPaginationHelper.class);
        Mockito.when(helper.fetchPage(Mockito.anyString(), Mockito.anyString(), Mockito.any(),
            Mockito.anyInt(), Mockito.anyInt(), Mockito.any())).thenAnswer(invocation -> {
                matched.addAll(query(invocation.getArgument(1), invocation.getArgument(2)));
                return new Page<RoleInfo>();
            });
        return new EmbeddedRolePersistServiceImpl(Mockito.mock(DatabaseOperate.class)) {
            
            @Override
            public <E> AuthPaginationHelper<E> createPaginationHelper() {
                return (AuthPaginationHelper<E>) helper;
            }
        };
    }
    
    private List<String> query(String sql, Object[] args) throws SQLException {
        List<String> rows = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            for (int i = 0; i < args.length; i++) {
                statement.setObject(i + 1, args[i]);
            }
            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    rows.add(resultSet.getString("username") + "/" + resultSet.getString("role"));
                }
            }
        }
        return rows;
    }
}
