/*
 * Copyright 1999-2020 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nacos_grpc_service.proto

package com.alibaba.nacos.api.grpc.auto;

/**
 * Protobuf type {@code Metadata}
 */
public final class Metadata extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Metadata)
        MetadataOrBuilder {
    
    // Use Metadata.newBuilder() to construct.
    private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    
    private Metadata() {
        clientIp_ = "";
        clientPort_ = 0;
        type_ = "";
        connectionId_ = "";
        clientVersion_ = "";
    }
    
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    
    private Metadata(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();
        
                        clientIp_ = s;
                        break;
                    }
                    case 16: {
        
                        clientPort_ = input.readInt32();
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();
    
                        type_ = s;
                        break;
                    }
                    case 34: {
                        java.lang.String s = input.readStringRequireUtf8();
                        
                        connectionId_ = s;
                        break;
                    }
                    case 42: {
                        java.lang.String s = input.readStringRequireUtf8();
                        
                        clientVersion_ = s;
                        break;
                    }
                    case 50: {
                        if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                            labels_ = com.google.protobuf.MapField.newMapField(LabelsDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000020;
                        }
                        com.google.protobuf.MapEntry<java.lang.String, java.lang.String> labels__ = input
                                .readMessage(LabelsDefaultEntryHolder.defaultEntry.getParserForType(),
                                        extensionRegistry);
                        labels_.getMutableMap().put(labels__.getKey(), labels__.getValue());
                        break;
                    }
                    case 58: {
                        if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                            headers_ = com.google.protobuf.MapField.newMapField(HeadersDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000040;
                        }
                        com.google.protobuf.MapEntry<java.lang.String, java.lang.String> headers__ = input
                                .readMessage(HeadersDefaultEntryHolder.defaultEntry.getParserForType(),
                                        extensionRegistry);
                        headers_.getMutableMap().put(headers__.getKey(), headers__.getValue());
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.alibaba.nacos.api.grpc.auto.NacosGrpcService.internal_static_Metadata_descriptor;
    }
    
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(int number) {
        switch (number) {
            case 6:
                return internalGetLabels();
            case 7:
                return internalGetHeaders();
            default:
                throw new RuntimeException("Invalid map field number: " + number);
        }
    }
    
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.alibaba.nacos.api.grpc.auto.NacosGrpcService.internal_static_Metadata_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.alibaba.nacos.api.grpc.auto.Metadata.class,
                        com.alibaba.nacos.api.grpc.auto.Metadata.Builder.class);
    }
    
    private int bitField0_;
    
    public static final int CLIENT_IP_FIELD_NUMBER = 1;
    
    private volatile java.lang.Object clientIp_;
    
    /**
     * <code>string client_ip = 1;</code>
     */
    public java.lang.String getClientIp() {
        java.lang.Object ref = clientIp_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientIp_ = s;
            return s;
        }
    }
    
    /**
     * <code>string client_ip = 1;</code>
     */
    public com.google.protobuf.ByteString getClientIpBytes() {
        java.lang.Object ref = clientIp_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            clientIp_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int CLIENT_PORT_FIELD_NUMBER = 2;
    
    private int clientPort_;
    
    /**
     * <code>int32 client_port = 2;</code>
     */
    public int getClientPort() {
        return clientPort_;
    }
    
    public static final int TYPE_FIELD_NUMBER = 3;
    
    private volatile java.lang.Object type_;
    
    /**
     * <code>string type = 3;</code>
     */
    public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            type_ = s;
            return s;
        }
    }
    
    /**
     * <code>string type = 3;</code>
     */
    public com.google.protobuf.ByteString getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            type_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int CONNECTION_ID_FIELD_NUMBER = 4;
    
    private volatile java.lang.Object connectionId_;
    
    /**
     * <code>string connection_id = 4;</code>
     */
    public java.lang.String getConnectionId() {
        java.lang.Object ref = connectionId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            connectionId_ = s;
            return s;
        }
    }
    
    /**
     * <code>string connection_id = 4;</code>
     */
    public com.google.protobuf.ByteString getConnectionIdBytes() {
        java.lang.Object ref = connectionId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            connectionId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int CLIENT_VERSION_FIELD_NUMBER = 5;
    
    private volatile java.lang.Object clientVersion_;
    
    /**
     * <code>string client_version = 5;</code>
     */
    public java.lang.String getClientVersion() {
        java.lang.Object ref = clientVersion_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientVersion_ = s;
            return s;
        }
    }
    
    /**
     * <code>string client_version = 5;</code>
     */
    public com.google.protobuf.ByteString getClientVersionBytes() {
        java.lang.Object ref = clientVersion_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            clientVersion_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int LABELS_FIELD_NUMBER = 6;
    
    private static final class LabelsDefaultEntryHolder {
        
        static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry = com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
                com.alibaba.nacos.api.grpc.auto.NacosGrpcService.internal_static_Metadata_LabelsEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING, "", com.google.protobuf.WireFormat.FieldType.STRING,
                "");
    }
    
    private com.google.protobuf.MapField<java.lang.String, java.lang.String> labels_;
    
    private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetLabels() {
        if (labels_ == null) {
            return com.google.protobuf.MapField.emptyMapField(LabelsDefaultEntryHolder.defaultEntry);
        }
        return labels_;
    }
    
    public int getLabelsCount() {
        return internalGetLabels().getMap().size();
    }
    
    /**
     * <code>map&lt;string, string&gt; labels = 6;</code>
     */
    
    public boolean containsLabels(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        return internalGetLabels().getMap().containsKey(key);
    }
    
    /**
     * Use {@link #getLabelsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getLabels() {
        return getLabelsMap();
    }
    
    /**
     * <code>map&lt;string, string&gt; labels = 6;</code>
     */
    
    public java.util.Map<java.lang.String, java.lang.String> getLabelsMap() {
        return internalGetLabels().getMap();
    }
    
    /**
     * <code>map&lt;string, string&gt; labels = 6;</code>
     */
    
    public java.lang.String getLabelsOrDefault(java.lang.String key, java.lang.String defaultValue) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map = internalGetLabels().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    
    /**
     * <code>map&lt;string, string&gt; labels = 6;</code>
     */
    
    public java.lang.String getLabelsOrThrow(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map = internalGetLabels().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }
    
    public static final int HEADERS_FIELD_NUMBER = 7;
    
    private static final class HeadersDefaultEntryHolder {
        
        static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry = com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
                com.alibaba.nacos.api.grpc.auto.NacosGrpcService.internal_static_Metadata_HeadersEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING, "", com.google.protobuf.WireFormat.FieldType.STRING,
                "");
    }
    
    private com.google.protobuf.MapField<java.lang.String, java.lang.String> headers_;
    
    private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetHeaders() {
        if (headers_ == null) {
            return com.google.protobuf.MapField.emptyMapField(HeadersDefaultEntryHolder.defaultEntry);
        }
        return headers_;
    }
    
    public int getHeadersCount() {
        return internalGetHeaders().getMap().size();
    }
    
    /**
     * <code>map&lt;string, string&gt; headers = 7;</code>
     */
    
    public boolean containsHeaders(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        return internalGetHeaders().getMap().containsKey(key);
    }
    
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
        return getHeadersMap();
    }
    
    /**
     * <code>map&lt;string, string&gt; headers = 7;</code>
     */
    
    public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
        return internalGetHeaders().getMap();
    }
    
    /**
     * <code>map&lt;string, string&gt; headers = 7;</code>
     */
    
    public java.lang.String getHeadersOrDefault(java.lang.String key, java.lang.String defaultValue) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map = internalGetHeaders().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    
    /**
     * <code>map&lt;string, string&gt; headers = 7;</code>
     */
    
    public java.lang.String getHeadersOrThrow(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map = internalGetHeaders().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }
    
    private byte memoizedIsInitialized = -1;
    
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }
        
        memoizedIsInitialized = 1;
        return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!getClientIpBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientIp_);
        }
        if (clientPort_ != 0) {
            output.writeInt32(2, clientPort_);
        }
        if (!getTypeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
        }
        if (!getConnectionIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, connectionId_);
        }
        if (!getClientVersionBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, clientVersion_);
        }
        com.google.protobuf.GeneratedMessageV3
                .serializeStringMapTo(output, internalGetLabels(), LabelsDefaultEntryHolder.defaultEntry, 6);
        com.google.protobuf.GeneratedMessageV3
                .serializeStringMapTo(output, internalGetHeaders(), HeadersDefaultEntryHolder.defaultEntry, 7);
    }
    
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }
        
        size = 0;
        if (!getClientIpBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientIp_);
        }
        if (clientPort_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, clientPort_);
        }
        if (!getTypeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
        }
        if (!getConnectionIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, connectionId_);
        }
        if (!getClientVersionBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, clientVersion_);
        }
        for (java.util.Map.Entry<java.lang.String, java.lang.String> entry : internalGetLabels().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String> labels__ = LabelsDefaultEntryHolder.defaultEntry
                    .newBuilderForType().setKey(entry.getKey()).setValue(entry.getValue()).build();
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(6, labels__);
        }
        for (java.util.Map.Entry<java.lang.String, java.lang.String> entry : internalGetHeaders().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String> headers__ = HeadersDefaultEntryHolder.defaultEntry
                    .newBuilderForType().setKey(entry.getKey()).setValue(entry.getValue()).build();
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(7, headers__);
        }
        memoizedSize = size;
        return size;
    }
    
    private static final long serialVersionUID = 0L;
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.alibaba.nacos.api.grpc.auto.Metadata)) {
            return super.equals(obj);
        }
        com.alibaba.nacos.api.grpc.auto.Metadata other = (com.alibaba.nacos.api.grpc.auto.Metadata) obj;
        
        boolean result = true;
        result = result && getClientIp().equals(other.getClientIp());
        result = result && (getClientPort() == other.getClientPort());
        result = result && getType().equals(other.getType());
        result = result && getConnectionId().equals(other.getConnectionId());
        result = result && getClientVersion().equals(other.getClientVersion());
        result = result && internalGetLabels().equals(other.internalGetLabels());
        result = result && internalGetHeaders().equals(other.internalGetHeaders());
        return result;
    }
    
    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CLIENT_IP_FIELD_NUMBER;
        hash = (53 * hash) + getClientIp().hashCode();
        hash = (37 * hash) + CLIENT_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getClientPort();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
        hash = (37 * hash) + CONNECTION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getConnectionId().hashCode();
        hash = (37 * hash) + CLIENT_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getClientVersion().hashCode();
        if (!internalGetLabels().getMap().isEmpty()) {
            hash = (37 * hash) + LABELS_FIELD_NUMBER;
            hash = (53 * hash) + internalGetLabels().hashCode();
        }
        if (!internalGetHeaders().getMap().isEmpty()) {
            hash = (37 * hash) + HEADERS_FIELD_NUMBER;
            hash = (53 * hash) + internalGetHeaders().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    public Builder newBuilderForType() {
        return newBuilder();
    }
    
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    
    public static Builder newBuilder(com.alibaba.nacos.api.grpc.auto.Metadata prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }
    
    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    
    /**
     * Protobuf type {@code Metadata}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Metadata)
            com.alibaba.nacos.api.grpc.auto.MetadataOrBuilder {
        
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.alibaba.nacos.api.grpc.auto.NacosGrpcService.internal_static_Metadata_descriptor;
        }
        
        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(int number) {
            switch (number) {
                case 6:
                    return internalGetLabels();
                case 7:
                    return internalGetHeaders();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }
        
        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
            switch (number) {
                case 6:
                    return internalGetMutableLabels();
                case 7:
                    return internalGetMutableHeaders();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }
        
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.alibaba.nacos.api.grpc.auto.NacosGrpcService.internal_static_Metadata_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.alibaba.nacos.api.grpc.auto.Metadata.class,
                            com.alibaba.nacos.api.grpc.auto.Metadata.Builder.class);
        }
        
        // Construct using com.alibaba.nacos.api.grpc.auto.Metadata.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }
        
        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }
        
        public Builder clear() {
            super.clear();
            clientIp_ = "";
    
            clientPort_ = 0;
            
            type_ = "";
            
            connectionId_ = "";
            
            clientVersion_ = "";
            
            internalGetMutableLabels().clear();
            internalGetMutableHeaders().clear();
            return this;
        }
        
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.alibaba.nacos.api.grpc.auto.NacosGrpcService.internal_static_Metadata_descriptor;
        }
        
        public com.alibaba.nacos.api.grpc.auto.Metadata getDefaultInstanceForType() {
            return com.alibaba.nacos.api.grpc.auto.Metadata.getDefaultInstance();
        }
        
        public com.alibaba.nacos.api.grpc.auto.Metadata build() {
            com.alibaba.nacos.api.grpc.auto.Metadata result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }
        
        public com.alibaba.nacos.api.grpc.auto.Metadata buildPartial() {
            com.alibaba.nacos.api.grpc.auto.Metadata result = new com.alibaba.nacos.api.grpc.auto.Metadata(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.clientIp_ = clientIp_;
            result.clientPort_ = clientPort_;
            result.type_ = type_;
            result.connectionId_ = connectionId_;
            result.clientVersion_ = clientVersion_;
            result.labels_ = internalGetLabels();
            result.labels_.makeImmutable();
            result.headers_ = internalGetHeaders();
            result.headers_.makeImmutable();
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }
        
        public Builder clone() {
            return (Builder) super.clone();
        }
        
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return (Builder) super.setField(field, value);
        }
        
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }
        
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }
        
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }
        
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.alibaba.nacos.api.grpc.auto.Metadata) {
                return mergeFrom((com.alibaba.nacos.api.grpc.auto.Metadata) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }
        
        public Builder mergeFrom(com.alibaba.nacos.api.grpc.auto.Metadata other) {
            if (other == com.alibaba.nacos.api.grpc.auto.Metadata.getDefaultInstance()) {
                return this;
            }
            if (!other.getClientIp().isEmpty()) {
                clientIp_ = other.clientIp_;
                onChanged();
            }
            if (other.getClientPort() != 0) {
                setClientPort(other.getClientPort());
            }
            if (!other.getType().isEmpty()) {
                type_ = other.type_;
                onChanged();
            }
            if (!other.getConnectionId().isEmpty()) {
                connectionId_ = other.connectionId_;
                onChanged();
            }
            if (!other.getClientVersion().isEmpty()) {
                clientVersion_ = other.clientVersion_;
                onChanged();
            }
            internalGetMutableLabels().mergeFrom(other.internalGetLabels());
            internalGetMutableHeaders().mergeFrom(other.internalGetHeaders());
            onChanged();
            return this;
        }
        
        public final boolean isInitialized() {
            return true;
        }
        
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            com.alibaba.nacos.api.grpc.auto.Metadata parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.alibaba.nacos.api.grpc.auto.Metadata) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }
        
        private int bitField0_;
    
        private java.lang.Object clientIp_ = "";
        
        /**
         * <code>string client_ip = 1;</code>
         */
        public java.lang.String getClientIp() {
            java.lang.Object ref = clientIp_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                clientIp_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <code>string client_ip = 1;</code>
         */
        public com.google.protobuf.ByteString getClientIpBytes() {
            java.lang.Object ref = clientIp_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                clientIp_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <code>string client_ip = 1;</code>
         */
        public Builder setClientIp(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
    
            clientIp_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <code>string client_ip = 1;</code>
         */
        public Builder clearClientIp() {
    
            clientIp_ = getDefaultInstance().getClientIp();
            onChanged();
            return this;
        }
        
        /**
         * <code>string client_ip = 1;</code>
         */
        public Builder setClientIpBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
    
            clientIp_ = value;
            onChanged();
            return this;
        }
    
        private int clientPort_;
    
        /**
         * <code>int32 client_port = 2;</code>
         */
        public int getClientPort() {
            return clientPort_;
        }
    
        /**
         * <code>int32 client_port = 2;</code>
         */
        public Builder setClientPort(int value) {
        
            clientPort_ = value;
            onChanged();
            return this;
        }
    
        /**
         * <code>int32 client_port = 2;</code>
         */
        public Builder clearClientPort() {
        
            clientPort_ = 0;
            onChanged();
            return this;
        }
    
        private java.lang.Object type_ = "";
        
        /**
         * <code>string type = 3;</code>
         */
        public java.lang.String getType() {
            java.lang.Object ref = type_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                type_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <code>string type = 3;</code>
         */
        public com.google.protobuf.ByteString getTypeBytes() {
            java.lang.Object ref = type_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                type_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <code>string type = 3;</code>
         */
        public Builder setType(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
    
            type_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <code>string type = 3;</code>
         */
        public Builder clearType() {
    
            type_ = getDefaultInstance().getType();
            onChanged();
            return this;
        }
        
        /**
         * <code>string type = 3;</code>
         */
        public Builder setTypeBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
    
            type_ = value;
            onChanged();
            return this;
        }
        
        private java.lang.Object connectionId_ = "";
        
        /**
         * <code>string connection_id = 4;</code>
         */
        public java.lang.String getConnectionId() {
            java.lang.Object ref = connectionId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                connectionId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <code>string connection_id = 4;</code>
         */
        public com.google.protobuf.ByteString getConnectionIdBytes() {
            java.lang.Object ref = connectionId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                connectionId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <code>string connection_id = 4;</code>
         */
        public Builder setConnectionId(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            
            connectionId_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <code>string connection_id = 4;</code>
         */
        public Builder clearConnectionId() {
            
            connectionId_ = getDefaultInstance().getConnectionId();
            onChanged();
            return this;
        }
        
        /**
         * <code>string connection_id = 4;</code>
         */
        public Builder setConnectionIdBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            
            connectionId_ = value;
            onChanged();
            return this;
        }
        
        private java.lang.Object clientVersion_ = "";
        
        /**
         * <code>string client_version = 5;</code>
         */
        public java.lang.String getClientVersion() {
            java.lang.Object ref = clientVersion_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                clientVersion_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <code>string client_version = 5;</code>
         */
        public com.google.protobuf.ByteString getClientVersionBytes() {
            java.lang.Object ref = clientVersion_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                clientVersion_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <code>string client_version = 5;</code>
         */
        public Builder setClientVersion(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            
            clientVersion_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <code>string client_version = 5;</code>
         */
        public Builder clearClientVersion() {
            
            clientVersion_ = getDefaultInstance().getClientVersion();
            onChanged();
            return this;
        }
        
        /**
         * <code>string client_version = 5;</code>
         */
        public Builder setClientVersionBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            
            clientVersion_ = value;
            onChanged();
            return this;
        }
        
        private com.google.protobuf.MapField<java.lang.String, java.lang.String> labels_;
        
        private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetLabels() {
            if (labels_ == null) {
                return com.google.protobuf.MapField.emptyMapField(LabelsDefaultEntryHolder.defaultEntry);
            }
            return labels_;
        }
        
        private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetMutableLabels() {
            onChanged();
            ;
            if (labels_ == null) {
                labels_ = com.google.protobuf.MapField.newMapField(LabelsDefaultEntryHolder.defaultEntry);
            }
            if (!labels_.isMutable()) {
                labels_ = labels_.copy();
            }
            return labels_;
        }
        
        public int getLabelsCount() {
            return internalGetLabels().getMap().size();
        }
        
        /**
         * <code>map&lt;string, string&gt; labels = 6;</code>
         */
        
        public boolean containsLabels(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetLabels().getMap().containsKey(key);
        }
        
        /**
         * Use {@link #getLabelsMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getLabels() {
            return getLabelsMap();
        }
        
        /**
         * <code>map&lt;string, string&gt; labels = 6;</code>
         */
        
        public java.util.Map<java.lang.String, java.lang.String> getLabelsMap() {
            return internalGetLabels().getMap();
        }
        
        /**
         * <code>map&lt;string, string&gt; labels = 6;</code>
         */
        
        public java.lang.String getLabelsOrDefault(java.lang.String key, java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map = internalGetLabels().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        
        /**
         * <code>map&lt;string, string&gt; labels = 6;</code>
         */
        
        public java.lang.String getLabelsOrThrow(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map = internalGetLabels().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }
        
        public Builder clearLabels() {
            internalGetMutableLabels().getMutableMap().clear();
            return this;
        }
        
        /**
         * <code>map&lt;string, string&gt; labels = 6;</code>
         */
        
        public Builder removeLabels(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableLabels().getMutableMap().remove(key);
            return this;
        }
        
        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getMutableLabels() {
            return internalGetMutableLabels().getMutableMap();
        }
        
        /**
         * <code>map&lt;string, string&gt; labels = 6;</code>
         */
        public Builder putLabels(java.lang.String key, java.lang.String value) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            if (value == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableLabels().getMutableMap().put(key, value);
            return this;
        }
        
        /**
         * <code>map&lt;string, string&gt; labels = 6;</code>
         */
        
        public Builder putAllLabels(java.util.Map<java.lang.String, java.lang.String> values) {
            internalGetMutableLabels().getMutableMap().putAll(values);
            return this;
        }
        
        private com.google.protobuf.MapField<java.lang.String, java.lang.String> headers_;
        
        private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetHeaders() {
            if (headers_ == null) {
                return com.google.protobuf.MapField.emptyMapField(HeadersDefaultEntryHolder.defaultEntry);
            }
            return headers_;
        }
        
        private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetMutableHeaders() {
            onChanged();
            ;
            if (headers_ == null) {
                headers_ = com.google.protobuf.MapField.newMapField(HeadersDefaultEntryHolder.defaultEntry);
            }
            if (!headers_.isMutable()) {
                headers_ = headers_.copy();
            }
            return headers_;
        }
        
        public int getHeadersCount() {
            return internalGetHeaders().getMap().size();
        }
        
        /**
         * <code>map&lt;string, string&gt; headers = 7;</code>
         */
        
        public boolean containsHeaders(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetHeaders().getMap().containsKey(key);
        }
        
        /**
         * Use {@link #getHeadersMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
            return getHeadersMap();
        }
        
        /**
         * <code>map&lt;string, string&gt; headers = 7;</code>
         */
        
        public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
            return internalGetHeaders().getMap();
        }
        
        /**
         * <code>map&lt;string, string&gt; headers = 7;</code>
         */
        
        public java.lang.String getHeadersOrDefault(java.lang.String key, java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map = internalGetHeaders().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        
        /**
         * <code>map&lt;string, string&gt; headers = 7;</code>
         */
        
        public java.lang.String getHeadersOrThrow(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map = internalGetHeaders().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }
        
        public Builder clearHeaders() {
            internalGetMutableHeaders().getMutableMap().clear();
            return this;
        }
        
        /**
         * <code>map&lt;string, string&gt; headers = 7;</code>
         */
        
        public Builder removeHeaders(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableHeaders().getMutableMap().remove(key);
            return this;
        }
        
        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getMutableHeaders() {
            return internalGetMutableHeaders().getMutableMap();
        }
        
        /**
         * <code>map&lt;string, string&gt; headers = 7;</code>
         */
        public Builder putHeaders(java.lang.String key, java.lang.String value) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            if (value == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableHeaders().getMutableMap().put(key, value);
            return this;
        }
        
        /**
         * <code>map&lt;string, string&gt; headers = 7;</code>
         */
        
        public Builder putAllHeaders(java.util.Map<java.lang.String, java.lang.String> values) {
            internalGetMutableHeaders().getMutableMap().putAll(values);
            return this;
        }
        
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }
        
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }
        
        // @@protoc_insertion_point(builder_scope:Metadata)
    }
    
    // @@protoc_insertion_point(class_scope:Metadata)
    private static final com.alibaba.nacos.api.grpc.auto.Metadata DEFAULT_INSTANCE;
    
    static {
        DEFAULT_INSTANCE = new com.alibaba.nacos.api.grpc.auto.Metadata();
    }
    
    public static com.alibaba.nacos.api.grpc.auto.Metadata getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }
    
    private static final com.google.protobuf.Parser<Metadata> PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
        public Metadata parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Metadata(input, extensionRegistry);
        }
    };
    
    public static com.google.protobuf.Parser<Metadata> parser() {
        return PARSER;
    }
    
    @java.lang.Override
    public com.google.protobuf.Parser<Metadata> getParserForType() {
        return PARSER;
    }
    
    public com.alibaba.nacos.api.grpc.auto.Metadata getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

