// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: naming_grpc_service.proto

package com.alibaba.nacos.naming.grpc;

public interface InstanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Instance)
    com.google.protobuf.MessageOrBuilder {
}
